
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.assets
{
public partial class TBAssetsPathData
{
    private readonly System.Collections.Generic.Dictionary<int, assets.AssetsPathData> _dataMap;
    private readonly System.Collections.Generic.List<assets.AssetsPathData> _dataList;
    
    public TBAssetsPathData(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, assets.AssetsPathData>();
        _dataList = new System.Collections.Generic.List<assets.AssetsPathData>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            assets.AssetsPathData _v;
            _v = global::GameConfig.assets.AssetsPathData.DeserializeAssetsPathData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, assets.AssetsPathData> DataMap => _dataMap;
    public System.Collections.Generic.List<assets.AssetsPathData> DataList => _dataList;

    public assets.AssetsPathData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public assets.AssetsPathData Get(int key) => _dataMap[key];
    public assets.AssetsPathData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

