//----------------------------------------------------------
// <auto-generated>
// -This code was generated.
// -Changes to this file may cause incorrect behavior.
// -will be lost if the code is regenerated.
// <auto-generated/>
//----------------------------------------------------------
using UnityEngine;
using UnityEngine.UI;
using TEngine;

namespace GameLogic
{
	[Window(UILayer.UI, location : "UIHome")]
	public partial class UIHome : UIWindow
	{
		#region 事件

		private partial void OnClickStartBtn()
		{
			Log.Info("click start btn");
			// GameModule.Scene.LoadSceneAsync("scene_battle").Forget();
			
			
			GameEvent.Send(EventHome.EnterBattle);
		}

		#endregion

		protected override void OnCreate()
		{
			base.OnCreate();
			
			Log.Info("UIHome OnCreate");
		}

		protected override void OnUpdate()
		{
			base.OnUpdate();
		}

		// protected override void OnSetVisible(bool visible)
		// {
		// 	base.OnSetVisible(visible);
		// }
	}
}

