
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class AssetsPathData : Luban.BeanBase
{
    public AssetsPathData(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ResourcesName = _buf.ReadString();
    }

    public static AssetsPathData DeserializeAssetsPathData(ByteBuf _buf)
    {
        return new AssetsPathData(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 资源名称
    /// </summary>
    public readonly string ResourcesName;
   
    public const int __ID__ = 1251974706;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "ResourcesName:" + ResourcesName + ","
        + "}";
    }
}
}

