
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    private assets.TBAssetsPathData m_TBAssetsPathData;
    public assets.TBAssetsPathData TBAssetsPathData 
    {
        get
        {
            if (m_TBAssetsPathData == null)
            {
                m_TBAssetsPathData = new assets.TBAssetsPathData(defaultLoader("assets_tbassetspathdata"));
                m_TBAssetsPathData.ResolveRef(this);
            }
            return m_TBAssetsPathData;
        }
        set
        {
            m_TBAssetsPathData = value;
            m_TBAssetsPathData.ResolveRef(this);
        }
    }
    private TbAssetsPathData m_TbAssetsPathData;
    public TbAssetsPathData TbAssetsPathData 
    {
        get
        {
            if (m_TbAssetsPathData == null)
            {
                m_TbAssetsPathData = new TbAssetsPathData(defaultLoader("tbassetspathdata"));
                m_TbAssetsPathData.ResolveRef(this);
            }
            return m_TbAssetsPathData;
        }
        set
        {
            m_TbAssetsPathData = value;
            m_TbAssetsPathData.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}
